#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=Trainmetatitan
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=1:00:00
#SBATCH --mem=32000M
#SBATCH --output=trainDPR.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/asymdpr/asymDPR
eval "$(conda shell.bash hook)"
conda activate asymdpr
python3 train_dpr.py



